version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
configuration: Release
platform: Any CPU

install: 
- cmd: nuget install redis-64 -excludeversion
- cmd: redis-64\tools\redis-server.exe --service-install 
- cmd: redis-64\tools\redis-server.exe --service-start
before_build:
- dotnet restore
build:
  project: Hangfire.Private.Redis.StackExchange.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: .\**\*.nupkg
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
test_script:
- dotnet test "Hangfire.Redis.Tests" -f netcoreapp1.0
- dotnet test "Hangfire.Redis.Tests" -f net451
before_package:
- ps: nuget pack .\Hangfire.Private.Redis.StackExchange\HangFire.Private.Redis.StackExchange.nuspec -Version $env:APPVEYOR_BUILD_VERSION
deploy:
  provider: NuGet
  api_key:
    secure: Wrq+QibneTq9Rvutd75Y7Hvf+UcJ3K/RA/cl1Eb4ViymauThEu1/g22002Bx4MHn
  artifact: /.*\.nupkg/
